workflows:
  android:
    name: Build Android App
    environment:
      flutter: stable
      java: 11
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android AAB
        script: |
          flutter build appbundle --release --build-name=1.0.0 --build-number=1 \
            --dart-define=CM_KEYSTORE_PASSWORD=$CM_KEYSTORE_PASSWORD \
            --dart-define=CM_KEY_ALIAS=$CM_KEY_ALIAS \
            --dart-define=CM_KEY_PASSWORD=$CM_KEY_PASSWORD
    artifacts:
      - build/app/outputs/bundle/release/*.aab
