workflows:
  android:
    name: Build Android App
    environment:
      flutter: 3.19.0
      java: 11
      android_signing:
        - silent_key
      groups:
        - google_credentials
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Update app.gradle with version info
        script: |
          APP_BUILD_NUMBER=$(($BUILD_NUMBER))
          APP_VERSION="1.0.$(($BUILD_NUMBER))"
          echo "Updating app.gradle with APP_VERSION: $APP_VERSION and APP_BUILD_NUMBER: $APP_BUILD_NUMBER"
          sed -i '' "s/versionCode [0-9][0-9]*/versionCode $APP_BUILD_NUMBER/" android/app/build.gradle
          sed -i '' "s/versionName \".*\"/versionName \"$APP_VERSION\"/" android/app/build.gradle
          echo "[{\"language\": \"en-US\", \"text\": \"Build type: staging, Version: $APP_VERSION, Build number: $APP_BUILD_NUMBER\"}]" > release_notes.json
          cat release_notes.json
      - name: Build Android AAB
        script: |
          flutter build appbundle --release
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $CM_BUILD_DIR/node_modules
        - $CM_BUILD_DIR/platforms
        - $CM_BUILD_DIR/hooks
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GOOGLE_CREDENTIALS
        track: internal
      email:
        recipients:
          - lakpriya1024@gmail.com
