name: Deploy to Google Play Store

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the JDK version

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Build Release APK
        run: ./gradlew assembleRelease  # Adjust this if you use a different build command

      - name: Upload release APK to Google Play
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > service-account.json
          gcloud auth activate-service-account --key-file service-account.json
          gcloud config set project ${{ secrets.GOOGLE_PLAY_PROJECT_ID }}
          gcloud alpha android apps releases create --track internal --version-code $(grep versionCode app/build.gradle | awk '{print $2}' | tr -d '()') --package app/build/outputs/apk/release/app-release.apk
